# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ffd30ad5d2086d819361fbd838ff730ced1e15acc7119c97de87e7761b444a82c90496a9b9a4d31ec48f8dc93a32c1bf81b261f2c645ba3be9b56907a3e5189

test:
  secret_key_base: d500e322fb39eea9db306ed0532942f9e685908794858b9a0278f1957d64fe5f021f74e44e6ed225970c0f316ab1d402f4510c5a86bdc3e10861dab67d9e2847

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
